'''
Extend Previous Exercises. Rework the exercies in Numeric Types and Expressions.
Each of the previous exercises can be rewritten to use variables instead of expressions
using only constants. For example, if you want to tackle the Farenheit to Celsius problem
youmight write something like this.

#!/usr/bin/python
#Convert 8 C to F
C = 8
F = 32 + C*(9.0/5.0)
print('Celcius', C, 'Farenheit', F)

You will want to rewrite those exercises using variables to get ready to input functions.
'''
#################################################
#Stock Exchange exercise
#For 125 shares
share = 125
price = 3 + 3/8
print(share * price)

#For 150 and 75 shares
share_1 = 150
share_2 = 75
price_1 = 2 + 1/4
price_2 = 1 + 7/8
print(share_1*price_1 + share_2*price_2)

###################################################
#temperature exercise
C = 18 #Celsius
F = -4 #Farenheit

#Farenheit conversion
print("F =", 32+(((212-32)/100)*C)) 
#Celsius conversion
print("C =", (F-32)*100/(212-32))

####################################################
# Mortgage exercise
#principal
p = 110000
#monthly interest rate
r = 7.25 / 12
#number of monthly payments
n = 30 * 12
#formula - I
m1 = p * r/(1-(1+r)**-n)
#formula - II
m2 = -r*p*(r+1)**n/(r+1)**n-1 
#formula - III
m3 = (-r*p*(r+1)**n)/((r+1)**n-1)*(r+1)

print('Cost of mortgage = ', int(m1))
print('Mortgage with payments due at the end of each period = ', int(m2))
print('Mortgage with paymens due at the beginning of each period = ', int(m3))

########################################################
#Diving exercise
#constant values
#starting pressure
s = 2500

#final pressure
f = 500

#SACR
c = 15.2

#time
d1, d2 = 60, 70

#time estimates
t1 = (33*(s-f))/(c*(d1 + 33))
t2 = (33*(s-f))/(c*(d2 + 33))

print('To dive 60 ft it will take: ', int(t1), 'minutes')
print('To dive 70 ft it will take: ', int(t2), 'minutes')

##########################################################
#sail surface area
a = 61

#wind speed
w = 15

#force of wind
f = w**2*0.004*a

print('Force generated by 61 sq.ft sail in 15mph wind: ', f)

#########################################################
#probability exercise


#########################################################
#Roulette exercise